codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto

  flags:
    unittests:
      paths:
        - Working_Gold/TASK_205/tests/unit/
      carryforward: true

    integration:
      paths:
        - Working_Gold/TASK_205/tests/integration/
      carryforward: true

    e2e:
      paths:
        - Working_Gold/TASK_205/tests/e2e/
      carryforward: true

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "**/__pycache__/"
  - "*.pyc"
  - ".pytest_cache/"
  - "htmlcov/"
  - "*.egg-info/"
  - "venv/"
  - "env/"

github_checks:
  annotations: true
