name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run E2E tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-e2e-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-e2e-
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Working_Gold/TASK_205/requirements-test.txt

      - name: Run E2E tests
        run: |
          cd Working_Gold/TASK_205
          pytest tests/e2e -v --maxfail=3 --tb=short
        timeout-minutes: 20

      - name: Run E2E tests with coverage
        if: success()
        run: |
          cd Working_Gold/TASK_205
          pytest tests/e2e --cov=. --cov-report=xml --cov-report=html

      - name: Upload E2E coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./Working_Gold/TASK_205/coverage.xml
          flags: e2e
          name: codecov-e2e
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-coverage-report
          path: Working_Gold/TASK_205/htmlcov/
          retention-days: 30

      - name: Generate E2E test report
        if: always()
        run: |
          cd Working_Gold/TASK_205
          pytest tests/e2e --html=e2e-report.html --self-contained-html

      - name: Upload E2E test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-report
          path: Working_Gold/TASK_205/e2e-report.html
          retention-days: 30

      - name: Performance benchmarks
        if: success()
        run: |
          cd Working_Gold/TASK_205
          pytest tests/e2e/test_performance_baselines.py -v -s > performance-results.txt

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-results
          path: Working_Gold/TASK_205/performance-results.txt
          retention-days: 90
