name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Working_Gold/TASK_205/requirements-test.txt

      - name: Run unit tests
        run: |
          cd Working_Gold/TASK_205
          pytest tests/unit -v --cov=. --cov-report=xml --cov-report=term-missing
        continue-on-error: false

      - name: Run integration tests
        run: |
          cd Working_Gold/TASK_205
          pytest tests/integration -v --cov=. --cov-append --cov-report=xml
        continue-on-error: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./Working_Gold/TASK_205/coverage.xml
          flags: unittests,integration
          name: codecov-${{ matrix.python-version }}
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate HTML coverage report
        run: |
          cd Working_Gold/TASK_205
          pytest tests/unit tests/integration --cov=. --cov-report=html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: Working_Gold/TASK_205/htmlcov/
          retention-days: 30

      - name: Check coverage threshold
        run: |
          cd Working_Gold/TASK_205
          pytest tests/unit tests/integration --cov=. --cov-fail-under=80
